#!/usr/bin/env bash
# Auto-generated by master_install_spark_jupyter.sh
export SPARK_HOME="/opt/spark"
export JAVA_HOME="/usr/lib/jvm/java-11-openjdk-amd64"
export HADOOP_HOME="/usr/local/hadoop"
export HADOOP_CONF_DIR="/usr/local/hadoop/etc/hadoop"
export PYSPARK_PYTHON="/usr/bin/python3.12"
if [[ -x "/usr/local/hadoop/bin/hadoop" ]]; then
  export SPARK_DIST_CLASSPATH="$('/usr/local/hadoop/bin/hadoop' classpath)"
fi
